config/routes.rb
TimeTrek::Application.routes.draw do
    resources :tasks  do
        patch 'complete'    => 'tasks#complete'
        patch 'uncomplete'  => 'tasks#uncomplete'
        patch 'flag'        => 'tasks#flag'
        patch 'unflag'      => 'tasks#unflag'
    end
    
    root 'tasks#index'

  

end

app/models/TaskStatus.rb
class TaskStatus
    def self.open
        "Open"
    end

    def self.completed
        "Completed"
    end
end

app/models/states/open.rb
class Open < State
end

app/models/states/state.rb
class State
    def to_s 
        name
    end

    def name
        self.class.name.split('::').last
    end
end

app/models/task.rb
require_relative 'taskstatus'

class Task < ActiveRecord::Base
    def self.open_flagged_tasks 
       Task.where(:status => TaskStatus.open, :flagged => true).order(:description)
    end

    def self.open_unflagged_tasks
        Task.where(:status => TaskStatus.open, :flagged => false).order(:description)
    end

    def self.open_tasks  
        Task.open_flagged_tasks + Task.open_unflagged_tasks
    end

    def self.completed_tasks()
        Task.where(status: TaskStatus.completed)
    end

    def complete
        self.status = TaskStatus.completed
        self.unflag
    end

    def uncomplete
        self.status = TaskStatus.open
    end

    def flag
        self.flagged = true
    end

    def unflag
        self.flagged = false
    end
end

app/models/taskstatus f.rb
class TaskStatus
    def self.open
        "Open"
    end

    def self.completed
        "Completed"
    end
end

app/models/taskstatus.rb
class TaskStatus
    def self.open
        "Open"
    end

    def self.completed
        "Completed"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :find_task, except: [:index, :create, :show]
    after_action :save_task, only: [:complete, :uncomplete, :flag, :unflag]

    def index
        @tasks = Task.open_tasks
        @completed_taks = Task.completed_tasks
    end

    def create
        Task.create!(description: create_task_params)
        redirect_to_task_list
    end

    def show
        @task = Task.find(params[:id])

        respond_to do |format|
            format.json { render :json => @task }
        end
    end

    def destroy
        @task.destroy
        redirect_to_task_list
    end

    def complete
        @task.complete
        redirect_to_task_list
    end

    def uncomplete
        @task.uncomplete
        redirect_to_task_list
    end

    def flag 
        @task.flag
        redirect_to_task_list
    end
    
    def unflag
        @task.unflag
        redirect_to_task_list
    end

    private 

    def create_task_params
        params.require(:description)
    end

    def redirect_to_task_list
        redirect_to tasks_url
    end

    def find_task
        @task = Task.find(params[:task_id])

        if @task == nil
            redirect_to_task_list
        end
    end

    def save_task
        @task.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="background-landscape-marvellous-butterfly">
    <head>
      <title>TimeTrek</title>
      <%= stylesheet_link_tag    "reset", "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
    </head>
    <body>
        <%= yield %>
    </body>
</html>

app/views/tasks/_closed_tasks.erb
<ul class="completed">
    <% @completed_taks.each do |task| %>
        <li class="task">
            <div>
                <%= link_to image_tag('/assets/boxes_checked.png'), 
                    task_uncomplete_path(task.id),
                    :method => :patch, 
                    :class => "checkbox" %>
                <%= 
                    if task.flagged
                        image_tag '/assets/flag.png', :class => "flag"
                    else
                        image_tag '/assets/flag not stared.png', :class => "flag"
                    end
                %>
                <span><%= task.description %></span> 
                <!-- <%= link_to 'X', task_path(task.id), :method => :delete %> -->
            </div>
        </li>
    <% end %>
</ul>

app/views/tasks/_open_tasks.erb
<ul class="open">
<% @tasks.each do |task| %>
    <li class="task" data-task-id="<%= task.id %>">
        <div>
            <%= link_to image_tag('/assets/boxes_normal.png'), 
                task_complete_path(task.id),
                :method => :patch, 
                :class => "checkbox" %>
            <%= 
                if task.flagged 
                    link_to image_tag('/assets/flag.png'), task_unflag_path(task.id), :method => :patch, :class => "flag" 
                else
                    link_to image_tag('/assets/flag not stared.png'), task_flag_path(task.id), :method => :patch, :class => "flag" 
                end    
            %>
        <span><%= task.description %></span> 
            <%= link_to image_tag('/assets/trashcan.png'), task_path(:task_id => task.id, :id => task.id), :method => :delete, :class => "delete" %>
        </div>
    </li>
<% end %>

app/views/tasks/_task_entry.erb
<div id="taskEntry">
    <input type="text" name="description" value="" action="saveTask" />
</div>

app/views/tasks/index.html.erb
    <div class="content">
        <div id="header">
            <%= render :partial => "task_entry" %>
        </div>
        <div id="task_lists">
            <div class="spacer"></div>
            <%= render :partial => "open_tasks" %>
            <%= render :partial => "closed_tasks" %>
        </div>
        <div id="task_details">
            <div class="task_background">
                <div id="task_description" ><span></span></div>
                <div id="stats">
                    <div id="created" class="stat">
                        <div class="label">Created Date:</div>
                        <div class="value"></div>
                    </div>
                    <div id="updated" class="stat">
                        <div class="label">Updated Date:</div>
                        <div class="value"></div>
                    </div>
                    <div id="status" class="stat">
                        <div class="label">Status:</div>
                        <div class="value"></div>
                    </div>
                </div>
                <div id="resources">
                    <textarea></textarea>
                </div>
            </div>
        </div>
    </div>
</script>